import patternCraftBackgrounds from "./data/patternCraftBackgrounds.json";

export interface CssBackgroundCatalogEntry {
  id: string;
  name: string;
  category: string;
  description?: string;
  badge?: string;
  style: Record<string, string>;
}

export interface CssBackgroundAssetSeed {
  name: string;
  type: "image";
  source: "css";
  category: string;
  tags: string[];
  /** SVG data URL encoding the full-res pattern (1080×1920) — infinitely scalable, zero bytes on disk */
  url: string;
  /** PNG file URL generated by Puppeteer at seed time (640×360) — set by the seed script after rendering */
  thumbnailUrl: string;
  filePath: string;
  mimeType: string;
  description: string;
  colorPalette: string[];
  /** Raw CSS style object — stored as JSONB for live rendering and customisation */
  cssStyle: Record<string, string>;
  embedText: string;
}

function camelToKebab(input: string): string {
  return input.replace(/[A-Z]/g, (match) => `-${match.toLowerCase()}`);
}

function escapeHtml(input: string): string {
  return input
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function cssBackgroundStyleToDataUrl(style: Record<string, string>, width: number, height: number): string {
  const css = Object.entries({
    width: "100%",
    height: "100%",
    ...style,
  })
    .map(([key, value]) => `${camelToKebab(key)}:${value}`)
    .join(";");

  const svg = `
<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}">
  <foreignObject x="0" y="0" width="${width}" height="${height}">
    <div xmlns="http://www.w3.org/1999/xhtml" style="${escapeHtml(css)}"></div>
  </foreignObject>
</svg>`;

  return `data:image/svg+xml;charset=utf-8,${encodeURIComponent(svg)}`;
}

function extractHexColors(style: Record<string, string>): string[] {
  const colorRegex = /#(?:[0-9a-fA-F]{3,8})\b/g;
  const seen = new Set<string>();
  const colors: string[] = [];
  for (const value of Object.values(style)) {
    for (const match of value.match(colorRegex) ?? []) {
      const normalized = match.toUpperCase();
      if (!seen.has(normalized)) {
        seen.add(normalized);
        colors.push(normalized);
      }
    }
  }
  return colors.slice(0, 6);
}

function tokenize(value: string): string[] {
  return value
    .split(/[^a-z0-9]+/i)
    .map((token) => token.trim().toLowerCase())
    .filter(Boolean);
}

function inferTags(entry: CssBackgroundCatalogEntry): string[] {
  const tags = new Set<string>([
    "background",
    "css",
    "pattern-craft",
    "video",
    "scene",
    entry.category.toLowerCase(),
  ]);

  const text = [entry.id, entry.name, entry.description, ...Object.values(entry.style)].filter(Boolean).join(" ");
  for (const token of tokenize(text)) {
    if (token.length >= 3) tags.add(token);
  }

  if (text.includes("radial-gradient")) tags.add("radial-gradient");
  if (text.includes("linear-gradient")) tags.add("linear-gradient");
  if (text.includes("grid")) tags.add("grid");
  if (text.includes("glow")) tags.add("glow");
  if (text.includes("dark")) tags.add("dark");
  if (text.includes("void") || text.includes("abyss") || text.includes("depth")) tags.add("moody");
  if (text.includes("overlay")) tags.add("overlay");

  return Array.from(tags).slice(0, 32);
}

function buildDescription(entry: CssBackgroundCatalogEntry, colorPalette: string[]): string {
  const paletteText = colorPalette.length ? ` Color palette: ${colorPalette.join(", ")}.` : "";
  return entry.description ?? `${entry.name} is a ${entry.category} CSS background preset for video scenes and motion design.${paletteText}`;
}

export function getCssBackgroundCatalog(): CssBackgroundCatalogEntry[] {
  return patternCraftBackgrounds as unknown as CssBackgroundCatalogEntry[];
}

export function buildCssBackgroundAssetSeed(entry: CssBackgroundCatalogEntry): CssBackgroundAssetSeed {
  const colorPalette = extractHexColors(entry.style);
  const description = buildDescription(entry, colorPalette);
  const tags = inferTags(entry);

  return {
    name: entry.name,
    type: "image",
    source: "css",
    category: entry.category,
    tags,
    url: cssBackgroundStyleToDataUrl(entry.style, 1080, 1920),
    thumbnailUrl: "", // filled in by seed script after Puppeteer renders the PNG
    filePath: `pattern-craft/${entry.id}.svg`,
    mimeType: "image/svg+xml",
    description,
    colorPalette,
    cssStyle: entry.style,
    embedText: [
      entry.name,
      description,
      `category ${entry.category}`,
      `tags ${tags.join(" ")}`,
      colorPalette.length ? `colors ${colorPalette.join(" ")}` : "",
      "css background preset for vertical video scenes reels tiktok shorts",
    ]
      .filter(Boolean)
      .join(". "),
  };
}
