/**
 * Seeds the font DB with the 25 curated Google Fonts.
 * Run: pnpm --filter @kwikk/font-manager seed
 * Safe to re-run — uses UPSERT internally.
 */
import { ensureSchema, insertFont, getPool } from "./db.js";
import type { FontInsert } from "./types.js";

const GOOGLE_FONTS: FontInsert[] = [
  // -------------------------------------------------------------------------
  // Sans-serif — Geometric
  // -------------------------------------------------------------------------
  {
    id: "inter",
    family: "Inter",
    label: "Inter",
    category: "sans-serif",
    subcategory: "geometric",
    source: "google",
    license: "OFL-1.1",
    designer: "Rasmus Andersson",
    year_released: 2016,
    google_font_family: "Inter",
    specimen_text: "The best interface is no interface",
    weights: [
      { weight: 300 }, { weight: 400 }, { weight: 400, style: "italic" },
      { weight: 500 }, { weight: 600 }, { weight: 700 }, { weight: 800 }, { weight: 900 },
    ],
    pair_category: "MINIMAL_SINGLE",
    pair_role: "headline",
    tags: ["clean", "minimal", "professional", "readable", "neutral", "tech", "modern"],
    industry_scores: {
      tech: 0.95, fintech: 0.9, saas: 0.95, healthcare: 0.85,
      editorial: 0.75, corporate: 0.9, fashion: 0.4, luxury: 0.3,
      education: 0.85, ecommerce: 0.8, sports: 0.6,
    },
    semantic_roles: { body: 0.95, caption: 0.95, headline: 0.8, accent: 0.6, display: 0.5 },
    pairings: [
      { paired_family: "Playfair Display", role: "body_heading", compatibility_score: 0.95 },
      { paired_family: "Bodoni Moda",      role: "body_heading", compatibility_score: 0.9 },
      { paired_family: "DM Serif Display", role: "body_heading", compatibility_score: 0.9 },
      { paired_family: "Space Grotesk",    role: "body_heading", compatibility_score: 0.85 },
    ],
  },
  {
    id: "dm-sans",
    family: "DM Sans",
    label: "DM Sans",
    category: "sans-serif",
    subcategory: "geometric",
    source: "google",
    license: "OFL-1.1",
    designer: "Colophon Foundry",
    year_released: 2019,
    google_font_family: "DM Sans",
    specimen_text: "Design is intelligence made visible",
    weights: [{ weight: 300 }, { weight: 400 }, { weight: 500 }, { weight: 600 }, { weight: 700 }],
    pair_category: "BOLD_IMPACT",
    pair_role: "body",
    tags: ["friendly", "approachable", "modern", "clean", "professional", "warm"],
    industry_scores: {
      saas: 0.9, lifestyle: 0.8, editorial: 0.75, tech: 0.85,
      wellness: 0.8, education: 0.8, ecommerce: 0.8, healthcare: 0.8,
    },
    semantic_roles: { body: 0.9, caption: 0.85, headline: 0.75, display: 0.6, accent: 0.65 },
    pairings: [
      { paired_family: "DM Serif Display", role: "body_heading", compatibility_score: 0.95 },
      { paired_family: "Playfair Display", role: "body_heading", compatibility_score: 0.85 },
    ],
  },
  {
    id: "space-grotesk",
    family: "Space Grotesk",
    label: "Space Grotesk",
    category: "sans-serif",
    subcategory: "geometric grotesque",
    source: "google",
    license: "OFL-1.1",
    designer: "Florian Karsten",
    year_released: 2020,
    google_font_family: "Space Grotesk",
    specimen_text: "Move fast, ship things",
    weights: [{ weight: 300 }, { weight: 400 }, { weight: 500 }, { weight: 600 }, { weight: 700 }],
    pair_category: "MODERN_CLEAN",
    pair_role: "headline",
    tags: ["technical", "futuristic", "bold", "digital", "modern", "distinctive", "edgy"],
    industry_scores: {
      tech: 0.9, crypto: 0.9, gaming: 0.8, fintech: 0.85,
      saas: 0.85, sports: 0.7, entertainment: 0.75,
    },
    semantic_roles: { headline: 0.9, display: 0.8, body: 0.75, caption: 0.7, accent: 0.75 },
    pairings: [
      { paired_family: "Inter",   role: "heading_body", compatibility_score: 0.85 },
      { paired_family: "Manrope", role: "heading_body", compatibility_score: 0.8 },
    ],
  },
  {
    id: "manrope",
    family: "Manrope",
    label: "Manrope",
    category: "sans-serif",
    subcategory: "geometric grotesque",
    source: "google",
    license: "OFL-1.1",
    designer: "Mikhail Sharanda",
    year_released: 2018,
    google_font_family: "Manrope",
    specimen_text: "Clarity in every character",
    weights: [{ weight: 300 }, { weight: 400 }, { weight: 500 }, { weight: 600 }, { weight: 700 }, { weight: 800 }],
    pair_category: "FRIENDLY_CONSUMER",
    pair_role: "body",
    tags: ["rounded", "friendly", "modern", "warm", "readable", "approachable"],
    industry_scores: {
      wellness: 0.85, lifestyle: 0.8, fintech: 0.75, saas: 0.8,
      education: 0.85, healthcare: 0.8, food: 0.75,
    },
    semantic_roles: { body: 0.9, caption: 0.85, headline: 0.75, accent: 0.6 },
    pairings: [
      { paired_family: "Space Grotesk",    role: "body_heading", compatibility_score: 0.8 },
      { paired_family: "Playfair Display", role: "body_heading", compatibility_score: 0.8 },
    ],
  },
  {
    id: "plus-jakarta-sans",
    family: "Plus Jakarta Sans",
    label: "Plus Jakarta Sans",
    category: "sans-serif",
    subcategory: "geometric",
    source: "google",
    license: "OFL-1.1",
    designer: "Tokotype",
    year_released: 2021,
    google_font_family: "Plus Jakarta Sans",
    specimen_text: "Professional precision, human touch",
    weights: [
      { weight: 300 }, { weight: 400 }, { weight: 500 }, { weight: 600 }, { weight: 700 }, { weight: 800 },
    ],
    pair_category: "BOLD_AUTHORITY",
    pair_role: "body",
    tags: ["corporate", "modern", "versatile", "professional", "clean", "polished"],
    industry_scores: {
      corporate: 0.9, saas: 0.85, fintech: 0.85, consulting: 0.9,
      healthcare: 0.8, legal: 0.8, enterprise: 0.85,
    },
    semantic_roles: { body: 0.85, headline: 0.8, caption: 0.8, display: 0.65 },
    pairings: [
      { paired_family: "Playfair Display", role: "body_heading", compatibility_score: 0.8 },
      { paired_family: "Bodoni Moda",      role: "body_heading", compatibility_score: 0.75 },
    ],
  },
  {
    id: "outfit",
    family: "Outfit",
    label: "Outfit",
    category: "sans-serif",
    subcategory: "geometric",
    source: "google",
    license: "OFL-1.1",
    designer: "Rodrigo Fuenzalida",
    year_released: 2021,
    google_font_family: "Outfit",
    specimen_text: "Fresh ideas, clean execution",
    weights: [
      { weight: 300 }, { weight: 400 }, { weight: 500 }, { weight: 600 },
      { weight: 700 }, { weight: 800 }, { weight: 900 },
    ],
    pair_category: "PREMIUM_EDITORIAL",
    pair_role: "body",
    tags: ["contemporary", "clean", "versatile", "modern", "neutral", "fresh"],
    industry_scores: {
      lifestyle: 0.85, fashion: 0.7, tech: 0.8, saas: 0.8,
      ecommerce: 0.8, wellness: 0.75, food: 0.75,
    },
    semantic_roles: { body: 0.85, headline: 0.8, caption: 0.8, display: 0.7 },
    pairings: [
      { paired_family: "Playfair Display", role: "body_heading", compatibility_score: 0.8 },
      { paired_family: "Lora",             role: "body_heading", compatibility_score: 0.75 },
    ],
  },
  {
    id: "nunito",
    family: "Nunito",
    label: "Nunito",
    category: "sans-serif",
    subcategory: "rounded",
    source: "google",
    license: "OFL-1.1",
    designer: "Vernon Adams",
    year_released: 2014,
    google_font_family: "Nunito",
    specimen_text: "Approachable, warm, and always clear",
    weights: [
      { weight: 300 }, { weight: 400 }, { weight: 500 }, { weight: 600 },
      { weight: 700 }, { weight: 800 }, { weight: 900 },
    ],
    pair_category: "FRIENDLY_CONSUMER",
    pair_role: "body",
    tags: ["friendly", "rounded", "approachable", "playful", "soft", "warm", "casual"],
    industry_scores: {
      education: 0.9, wellness: 0.85, lifestyle: 0.8, food: 0.75,
      children: 0.9, ecommerce: 0.7, healthcare: 0.75,
    },
    semantic_roles: { body: 0.85, caption: 0.8, headline: 0.7, accent: 0.65 },
    pairings: [
      { paired_family: "Playfair Display", role: "body_heading", compatibility_score: 0.75 },
      { paired_family: "Raleway",          role: "body_heading", compatibility_score: 0.8 },
    ],
  },
  {
    id: "poppins",
    family: "Poppins",
    label: "Poppins",
    category: "sans-serif",
    subcategory: "geometric",
    source: "google",
    license: "OFL-1.1",
    designer: "Indian Type Foundry",
    year_released: 2014,
    google_font_family: "Poppins",
    specimen_text: "Beautiful shapes, universal reach",
    weights: [
      { weight: 300 }, { weight: 400 }, { weight: 500 }, { weight: 600 },
      { weight: 700 }, { weight: 800 }, { weight: 900 },
    ],
    pair_category: "FRIENDLY_CONSUMER",
    pair_role: "headline",
    tags: ["versatile", "clean", "geometric", "professional", "fresh", "global", "warm"],
    industry_scores: {
      tech: 0.85, lifestyle: 0.85, fashion: 0.8, food: 0.8,
      ecommerce: 0.85, education: 0.8, wellness: 0.8, entertainment: 0.75,
    },
    semantic_roles: { headline: 0.85, body: 0.85, caption: 0.85, display: 0.75, accent: 0.7 },
    pairings: [
      { paired_family: "Playfair Display", role: "body_heading", compatibility_score: 0.85 },
      { paired_family: "Merriweather",     role: "body_heading", compatibility_score: 0.8 },
      { paired_family: "Lora",             role: "body_heading", compatibility_score: 0.8 },
    ],
  },
  {
    id: "raleway",
    family: "Raleway",
    label: "Raleway",
    category: "sans-serif",
    subcategory: "display sans",
    source: "google",
    license: "OFL-1.1",
    designer: "Matt McInerney",
    year_released: 2010,
    google_font_family: "Raleway",
    specimen_text: "Elegance in every weight",
    weights: [
      { weight: 300 }, { weight: 400 }, { weight: 500 }, { weight: 600 },
      { weight: 700 }, { weight: 800 }, { weight: 900 },
    ],
    pair_category: "ELEGANT_LIFESTYLE",
    pair_role: "headline",
    tags: ["elegant", "thin", "sophisticated", "clean", "artistic", "refined", "minimal"],
    industry_scores: {
      fashion: 0.85, luxury: 0.8, beauty: 0.85, wedding: 0.8,
      art: 0.8, lifestyle: 0.75, editorial: 0.75,
    },
    semantic_roles: { headline: 0.85, display: 0.8, body: 0.7, caption: 0.65, accent: 0.75 },
    pairings: [
      { paired_family: "Lora",         role: "heading_body", compatibility_score: 0.85 },
      { paired_family: "Merriweather", role: "heading_body", compatibility_score: 0.8 },
      { paired_family: "Nunito",       role: "heading_body", compatibility_score: 0.8 },
    ],
  },
  {
    id: "ibm-plex-sans",
    family: "IBM Plex Sans",
    label: "IBM Plex Sans",
    category: "sans-serif",
    subcategory: "humanist",
    source: "google",
    license: "OFL-1.1",
    designer: "Mike Abbink / Bold Monday",
    foundry: "IBM",
    year_released: 2017,
    google_font_family: "IBM Plex Sans",
    specimen_text: "Precision at every scale",
    weights: [{ weight: 300 }, { weight: 400 }, { weight: 500 }, { weight: 600 }, { weight: 700 }],
    pair_category: "ENERGETIC_MOTION",
    pair_role: "body",
    tags: ["technical", "corporate", "clean", "trustworthy", "professional", "precise", "neutral"],
    industry_scores: {
      enterprise: 0.95, fintech: 0.9, healthcare: 0.9,
      corporate: 0.9, consulting: 0.85, government: 0.85, tech: 0.85,
    },
    semantic_roles: { body: 0.9, caption: 0.9, headline: 0.8, accent: 0.6 },
    pairings: [
      { paired_family: "IBM Plex Sans",    role: "heading_body", compatibility_score: 0.9 },
      { paired_family: "Playfair Display", role: "body_heading", compatibility_score: 0.8 },
    ],
  },
  {
    id: "geist",
    family: "Geist",
    label: "Geist",
    category: "sans-serif",
    subcategory: "geometric",
    source: "google",
    license: "OFL-1.1",
    designer: "Vercel",
    foundry: "Vercel",
    year_released: 2023,
    google_font_family: "Geist",
    specimen_text: "Ship at the speed of thought",
    weights: [
      { weight: 300 }, { weight: 400 }, { weight: 500 }, { weight: 600 },
      { weight: 700 }, { weight: 800 }, { weight: 900 },
    ],
    pair_category: "MODERN_CLEAN",
    pair_role: "body",
    tags: ["minimal", "developer", "clean", "modern", "precise", "neutral", "future"],
    industry_scores: {
      tech: 0.95, saas: 0.9, developer_tools: 0.99, fintech: 0.8, corporate: 0.75,
    },
    semantic_roles: { body: 0.85, caption: 0.9, headline: 0.75, code: 0.8, accent: 0.6 },
    pairings: [
      { paired_family: "Bodoni Moda",      role: "body_heading", compatibility_score: 0.85 },
      { paired_family: "Playfair Display", role: "body_heading", compatibility_score: 0.8 },
    ],
  },
  {
    id: "montserrat",
    family: "Montserrat",
    label: "Montserrat",
    category: "sans-serif",
    subcategory: "geometric",
    source: "google",
    license: "OFL-1.1",
    designer: "Julieta Ulanovsky",
    year_released: 2011,
    google_font_family: "Montserrat",
    specimen_text: "Inspired by the old posters of Buenos Aires",
    weights: [
      { weight: 300 }, { weight: 400 }, { weight: 500 }, { weight: 600 },
      { weight: 700 }, { weight: 800 }, { weight: 900 },
    ],
    pair_category: "BOLD_AUTHORITY",
    pair_role: "headline",
    tags: ["bold", "clean", "versatile", "professional", "modern", "elegant", "poster"],
    industry_scores: {
      corporate: 0.85, fashion: 0.8, fitness: 0.8, food: 0.8,
      ecommerce: 0.85, entertainment: 0.8, lifestyle: 0.8,
    },
    semantic_roles: { headline: 0.9, display: 0.85, body: 0.8, caption: 0.8, accent: 0.7 },
    pairings: [
      { paired_family: "Merriweather",  role: "heading_body", compatibility_score: 0.85 },
      { paired_family: "Lora",         role: "heading_body", compatibility_score: 0.8 },
      { paired_family: "Inter",        role: "heading_body", compatibility_score: 0.8 },
    ],
  },

  // -------------------------------------------------------------------------
  // Serif
  // -------------------------------------------------------------------------
  {
    id: "playfair-display",
    family: "Playfair Display",
    label: "Playfair Display",
    category: "serif",
    subcategory: "transitional",
    source: "google",
    license: "OFL-1.1",
    designer: "Claus Eggers Sørensen",
    year_released: 2011,
    google_font_family: "Playfair Display",
    specimen_text: "Style is a way to say who you are",
    weights: [
      { weight: 400 }, { weight: 400, style: "italic" }, { weight: 500 },
      { weight: 600 }, { weight: 700 }, { weight: 800 }, { weight: 900 },
    ],
    pair_category: "PREMIUM_EDITORIAL",
    pair_role: "headline",
    tags: ["elegant", "luxury", "editorial", "sophisticated", "classic", "authoritative", "refined"],
    industry_scores: {
      luxury: 0.95, fashion: 0.9, editorial: 0.95, food: 0.85,
      wedding: 0.95, beauty: 0.9, lifestyle: 0.8, publishing: 0.85,
    },
    semantic_roles: { headline: 0.95, display: 0.9, body: 0.6, caption: 0.5, accent: 0.7 },
    pairings: [
      { paired_family: "Inter",          role: "heading_body", compatibility_score: 0.95 },
      { paired_family: "DM Sans",        role: "heading_body", compatibility_score: 0.9 },
      { paired_family: "Lora",           role: "heading_body", compatibility_score: 0.75 },
      { paired_family: "IBM Plex Sans",  role: "heading_body", compatibility_score: 0.8 },
    ],
  },
  {
    id: "lora",
    family: "Lora",
    label: "Lora",
    category: "serif",
    subcategory: "contemporary",
    source: "google",
    license: "OFL-1.1",
    designer: "Cyreal",
    year_released: 2011,
    google_font_family: "Lora",
    specimen_text: "Words worth reading, beautifully set",
    weights: [
      { weight: 400 }, { weight: 400, style: "italic" },
      { weight: 500 }, { weight: 600 }, { weight: 700 },
    ],
    pair_category: "ELEGANT_LIFESTYLE",
    pair_role: "body",
    tags: ["literary", "warm", "readable", "editorial", "organic", "humanist", "inviting"],
    industry_scores: {
      editorial: 0.9, publishing: 0.9, food: 0.8, lifestyle: 0.8,
      education: 0.85, wellness: 0.75, art: 0.8,
    },
    semantic_roles: { body: 0.9, headline: 0.8, caption: 0.7, display: 0.65 },
    pairings: [
      { paired_family: "Raleway",     role: "body_heading", compatibility_score: 0.85 },
      { paired_family: "Montserrat",  role: "body_heading", compatibility_score: 0.8 },
      { paired_family: "Poppins",     role: "body_heading", compatibility_score: 0.8 },
      { paired_family: "Outfit",      role: "body_heading", compatibility_score: 0.75 },
    ],
  },
  {
    id: "merriweather",
    family: "Merriweather",
    label: "Merriweather",
    category: "serif",
    subcategory: "slab",
    source: "google",
    license: "OFL-1.1",
    designer: "Eben Sorkin",
    year_released: 2010,
    google_font_family: "Merriweather",
    specimen_text: "Readable at every size, every screen",
    weights: [
      { weight: 300 }, { weight: 400 }, { weight: 400, style: "italic" },
      { weight: 700 }, { weight: 900 },
    ],
    pair_category: "BOLD_AUTHORITY",
    pair_role: "body",
    tags: ["readable", "editorial", "sturdy", "trustworthy", "classic", "newspaper", "authority"],
    industry_scores: {
      publishing: 0.9, news: 0.9, editorial: 0.85, education: 0.85,
      government: 0.8, legal: 0.8, corporate: 0.75,
    },
    semantic_roles: { body: 0.95, headline: 0.75, caption: 0.8, display: 0.6 },
    pairings: [
      { paired_family: "Montserrat",    role: "body_heading", compatibility_score: 0.85 },
      { paired_family: "Raleway",       role: "body_heading", compatibility_score: 0.8 },
      { paired_family: "IBM Plex Sans", role: "body_heading", compatibility_score: 0.8 },
    ],
  },
  {
    id: "dm-serif-display",
    family: "DM Serif Display",
    label: "DM Serif Display",
    category: "serif",
    subcategory: "transitional",
    source: "google",
    license: "OFL-1.1",
    designer: "Colophon Foundry",
    year_released: 2019,
    google_font_family: "DM Serif Display",
    specimen_text: "Designed to pair. Built to impress.",
    weights: [
      { weight: 400 }, { weight: 400, style: "italic" },
    ],
    pair_category: "PREMIUM_EDITORIAL",
    pair_role: "headline",
    tags: ["editorial", "elegant", "high-contrast", "sophisticated", "literary", "refined"],
    industry_scores: {
      luxury: 0.9, editorial: 0.9, fashion: 0.85, beauty: 0.8,
      lifestyle: 0.8, publishing: 0.8,
    },
    semantic_roles: { headline: 0.95, display: 0.9, body: 0.4, caption: 0.4, accent: 0.75 },
    pairings: [
      { paired_family: "DM Sans", role: "heading_body", compatibility_score: 0.95 },
      { paired_family: "Inter",   role: "heading_body", compatibility_score: 0.9 },
    ],
  },
  {
    id: "bodoni-moda",
    family: "Bodoni Moda",
    label: "Bodoni Moda",
    category: "serif",
    subcategory: "modern",
    source: "google",
    license: "OFL-1.1",
    designer: "Indestructible Type",
    year_released: 2020,
    google_font_family: "Bodoni Moda",
    specimen_text: "Fashion fades, style is eternal",
    weights: [
      { weight: 400 }, { weight: 400, style: "italic" }, { weight: 500 },
      { weight: 600 }, { weight: 700 }, { weight: 800 }, { weight: 900 },
    ],
    pair_category: "PREMIUM_EDITORIAL",
    pair_role: "headline",
    tags: ["high-fashion", "luxury", "editorial", "dramatic", "bold", "iconic", "contrast"],
    industry_scores: {
      luxury: 0.99, fashion: 0.95, beauty: 0.9, editorial: 0.85,
      jewelry: 0.95, lifestyle: 0.75, art: 0.8,
    },
    semantic_roles: { headline: 0.95, display: 0.95, body: 0.4, accent: 0.7, logo: 0.85 },
    pairings: [
      { paired_family: "Inter",         role: "heading_body", compatibility_score: 0.9 },
      { paired_family: "DM Sans",       role: "heading_body", compatibility_score: 0.9 },
      { paired_family: "Geist",         role: "heading_body", compatibility_score: 0.85 },
      { paired_family: "IBM Plex Sans", role: "heading_body", compatibility_score: 0.8 },
    ],
  },

  // -------------------------------------------------------------------------
  // Display
  // -------------------------------------------------------------------------
  {
    id: "bebas-neue",
    family: "Bebas Neue",
    label: "Bebas Neue",
    category: "display",
    subcategory: "condensed",
    source: "google",
    license: "OFL-1.1",
    designer: "Ryoichi Tsunekawa",
    year_released: 2010,
    google_font_family: "Bebas Neue",
    specimen_text: "MAKE SOME NOISE",
    weights: [{ weight: 400 }],
    pair_category: "BOLD_IMPACT",
    pair_role: "headline",
    tags: ["bold", "impactful", "urban", "energetic", "sporty", "loud", "all-caps", "street"],
    industry_scores: {
      sports: 0.95, fitness: 0.9, entertainment: 0.85, music: 0.85,
      gaming: 0.8, streetwear: 0.9, advertising: 0.85,
    },
    semantic_roles: { headline: 0.9, display: 0.95, body: 0.1, caption: 0.2, logo: 0.7 },
    pairings: [
      { paired_family: "Inter",    role: "heading_body", compatibility_score: 0.9 },
      { paired_family: "DM Sans", role: "heading_body", compatibility_score: 0.85 },
    ],
  },
  {
    id: "oswald",
    family: "Oswald",
    label: "Oswald",
    category: "display",
    subcategory: "condensed gothic",
    source: "google",
    license: "OFL-1.1",
    designer: "Vernon Adams",
    year_released: 2012,
    google_font_family: "Oswald",
    specimen_text: "STRENGTH IN EVERY LETTER",
    weights: [{ weight: 300 }, { weight: 400 }, { weight: 500 }, { weight: 600 }, { weight: 700 }],
    pair_category: "ENERGETIC_MOTION",
    pair_role: "headline",
    tags: ["powerful", "authoritative", "strong", "bold", "condensed", "versatile", "direct"],
    industry_scores: {
      sports: 0.9, news: 0.85, entertainment: 0.8, music: 0.8,
      government: 0.75, corporate: 0.7, fitness: 0.85,
    },
    semantic_roles: { headline: 0.9, display: 0.85, body: 0.4, caption: 0.3, accent: 0.6 },
    pairings: [
      { paired_family: "IBM Plex Sans", role: "heading_body", compatibility_score: 0.8 },
      { paired_family: "Merriweather", role: "heading_body", compatibility_score: 0.8 },
      { paired_family: "Lora",         role: "heading_body", compatibility_score: 0.75 },
    ],
  },
  {
    id: "barlow-condensed",
    family: "Barlow Condensed",
    label: "Barlow Condensed",
    category: "display",
    subcategory: "condensed",
    source: "google",
    license: "OFL-1.1",
    designer: "Jeremy Tribby",
    year_released: 2017,
    google_font_family: "Barlow Condensed",
    specimen_text: "Compact power, maximum expression",
    weights: [
      { weight: 300 }, { weight: 400 }, { weight: 500 }, { weight: 600 },
      { weight: 700 }, { weight: 800 }, { weight: 900 },
    ],
    pair_category: "ENERGETIC_MOTION",
    pair_role: "headline",
    tags: ["sporty", "versatile", "technical", "modern", "industrial", "condensed", "bold"],
    industry_scores: {
      sports: 0.9, fitness: 0.85, automotive: 0.8, tech: 0.75,
      military: 0.75, gaming: 0.8, entertainment: 0.75,
    },
    semantic_roles: { headline: 0.85, display: 0.8, body: 0.6, caption: 0.65, accent: 0.65 },
    pairings: [
      { paired_family: "Inter",    role: "heading_body", compatibility_score: 0.85 },
      { paired_family: "Manrope",  role: "heading_body", compatibility_score: 0.8 },
    ],
  },
  {
    id: "anton",
    family: "Anton",
    label: "Anton",
    category: "display",
    subcategory: "condensed impact",
    source: "google",
    license: "OFL-1.1",
    designer: "Vernon Adams",
    year_released: 2011,
    google_font_family: "Anton",
    specimen_text: "STOP SCROLLING",
    weights: [{ weight: 400 }],
    pair_category: "BOLD_IMPACT",
    pair_role: "headline",
    tags: ["bold", "impactful", "attention-grabbing", "poster", "aggressive", "loud", "all-caps"],
    industry_scores: {
      sports: 0.85, entertainment: 0.9, advertising: 0.9,
      streetwear: 0.85, music: 0.8, gaming: 0.75,
    },
    semantic_roles: { headline: 0.8, display: 0.95, body: 0.05, caption: 0.1, logo: 0.65 },
    pairings: [
      { paired_family: "Inter",    role: "heading_body", compatibility_score: 0.85 },
      { paired_family: "DM Sans",  role: "heading_body", compatibility_score: 0.8 },
    ],
  },

  // -------------------------------------------------------------------------
  // Monospace
  // -------------------------------------------------------------------------
  {
    id: "jetbrains-mono",
    family: "JetBrains Mono",
    label: "JetBrains Mono",
    category: "monospace",
    subcategory: "monospace",
    source: "google",
    license: "OFL-1.1",
    designer: "Philipp Nurullin",
    foundry: "JetBrains",
    year_released: 2020,
    google_font_family: "JetBrains Mono",
    specimen_text: "const ship = () => now();",
    weights: [
      { weight: 300 }, { weight: 400 }, { weight: 500 }, { weight: 600 },
      { weight: 700 }, { weight: 800 },
    ],
    pair_category: "MINIMAL_SINGLE",
    pair_role: "accent",
    tags: ["technical", "developer", "code", "precise", "minimal", "modern", "programming"],
    industry_scores: {
      tech: 0.95, developer_tools: 0.99, education: 0.7, saas: 0.75,
    },
    semantic_roles: { code: 0.99, caption: 0.6, body: 0.4, accent: 0.5 },
    pairings: [
      { paired_family: "Inter",        role: "body_heading", compatibility_score: 0.8 },
      { paired_family: "Space Grotesk", role: "body_heading", compatibility_score: 0.85 },
    ],
  },
  {
    id: "fira-code",
    family: "Fira Code",
    label: "Fira Code",
    category: "monospace",
    subcategory: "monospace",
    source: "google",
    license: "OFL-1.1",
    designer: "Nikita Prokopov",
    year_released: 2014,
    google_font_family: "Fira Code",
    specimen_text: "() => { return beautiful; }",
    weights: [{ weight: 300 }, { weight: 400 }, { weight: 500 }, { weight: 600 }, { weight: 700 }],
    pair_category: "MINIMAL_SINGLE",
    pair_role: "accent",
    tags: ["technical", "developer", "readable", "code", "distinctive", "ligatures", "programming"],
    industry_scores: {
      tech: 0.95, developer_tools: 0.99, education: 0.65,
    },
    semantic_roles: { code: 0.99, caption: 0.55, body: 0.35 },
    pairings: [
      { paired_family: "Inter",    role: "body_heading", compatibility_score: 0.8 },
      { paired_family: "Geist",    role: "body_heading", compatibility_score: 0.85 },
    ],
  },

  // -------------------------------------------------------------------------
  // Handwriting / Script
  // -------------------------------------------------------------------------
  {
    id: "pacifico",
    family: "Pacifico",
    label: "Pacifico",
    category: "handwriting",
    subcategory: "casual script",
    source: "google",
    license: "OFL-1.1",
    designer: "Vernon Adams",
    year_released: 2011,
    google_font_family: "Pacifico",
    specimen_text: "Good vibes only",
    weights: [{ weight: 400 }],
    pair_category: "FRIENDLY_CONSUMER",
    pair_role: "accent",
    tags: ["casual", "friendly", "retro", "fun", "tropical", "nostalgic", "playful", "surf"],
    industry_scores: {
      food: 0.85, lifestyle: 0.8, music: 0.75, entertainment: 0.7,
      children: 0.8, travel: 0.8, wellness: 0.6,
    },
    semantic_roles: { display: 0.8, headline: 0.7, accent: 0.75, logo: 0.8, body: 0.1 },
    pairings: [
      { paired_family: "Inter",  role: "heading_body", compatibility_score: 0.85 },
      { paired_family: "Nunito", role: "heading_body", compatibility_score: 0.8 },
    ],
  },
  {
    id: "dancing-script",
    family: "Dancing Script",
    label: "Dancing Script",
    category: "handwriting",
    subcategory: "formal script",
    source: "google",
    license: "OFL-1.1",
    designer: "Impallari Type",
    year_released: 2011,
    google_font_family: "Dancing Script",
    specimen_text: "Written with love",
    weights: [{ weight: 400 }, { weight: 500 }, { weight: 600 }, { weight: 700 }],
    pair_category: "ELEGANT_LIFESTYLE",
    pair_role: "accent",
    tags: ["elegant", "romantic", "feminine", "wedding", "handwritten", "artistic", "flowing"],
    industry_scores: {
      wedding: 0.9, beauty: 0.85, fashion: 0.8, food: 0.8,
      lifestyle: 0.75, art: 0.75, wellness: 0.7,
    },
    semantic_roles: { display: 0.85, headline: 0.75, accent: 0.8, logo: 0.75, body: 0.1 },
    pairings: [
      { paired_family: "Raleway",    role: "heading_body", compatibility_score: 0.85 },
      { paired_family: "Lora",       role: "heading_body", compatibility_score: 0.8 },
      { paired_family: "Montserrat", role: "heading_body", compatibility_score: 0.75 },
    ],
  },
];

async function main(): Promise<void> {
  await ensureSchema();
  console.log(`Seeding ${GOOGLE_FONTS.length} fonts...`);
  for (const font of GOOGLE_FONTS) {
    await insertFont(font);
    console.log(`  ✓ ${font.label}`);
  }
  console.log("Done.");
  await getPool().end();
}

main().catch((err) => { console.error(err); process.exit(1); });
